#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get install haproxy=2.6.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 487577-web-01 54.160.101.37:80 check
   server 487577-web-02 54.237.32.89:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
